name: Noip.Rocks
favicon: null
layout_spectrum: 0.90344
typography_spectrum: 0.14961
title: Noip.Rocks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d00000'
    - '#ffffff'
    - '#656565'
    - '#2f2f2f'
  brandStrength: 0.0625
  lightness: 0
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
